config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'users/create'
  get 'about/index'
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

  Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  
    get '/register', to: 'users#new'
    post '/register', to: 'users#create'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/signup', to: 'users#new'
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
  end

  get '/about', to: 'about#index', as: 'about'
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  before_action :authenticate

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
     username == ENV["USERNAME"] && password == ENV["PASSWORD"]
    end
  end

  def index
    @categories = Category.order(id: :desc).all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to [:admin, :categories], notice: 'Category created!'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(
      :name
    )
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Created At</th>
      <th>Updated At</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr class="category-list">
        <td><%= category.name %></td>
        <td><%= category.created_at %></td>
        <td><%= category.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Category", new_admin_category_path, class: 'new-cat'  %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= form_for [:admin, @category] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Create Category", class: "btn btn-primary" %>
<% end %>